<?xml version="1.0"?>
<robot name="cylinder" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="object_1_x" value="0.0" />
  <xacro:property name="object_1_y" value="0.0" />

  <xacro:property name="object_1_height"      value="1.2" />
  <xacro:property name="object_1_radius"      value="0.02" />
  <xacro:property name="object_1_base_height" value="0.02" />
  <xacro:property name="object_1_base_width"  value="0.15" />
  <xacro:property name="object_1_mass"        value="0.2" />
  <xacro:property name="object_1_mu"          value="500.0" />

  <link name="cylinder">
    <inertial>
      <mass value="${object_1_mass/2.0}" />
      <origin xyz="0 0 ${object_1_height/2}" />
      <inertia ixx="${object_1_mass/20.0}" ixy="0"  ixz="0"
               iyy="${object_1_mass/20.0}" iyz="0"
               izz="${object_1_mass/200.}" />
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 ${object_1_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${object_1_radius}" length="${object_1_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${object_1_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${object_1_radius}" length="${object_1_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="cylinder">
    <material>Gazebo/BumpyMetal</material>
    <mu1>${object_1_mu}</mu1>
    <mu2>${object_1_mu}</mu2>
    <kp>100000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
    <turnGravityOff>false</turnGravityOff>
    <dampingFactor>0.001</dampingFactor>
  </gazebo>

</robot>
