<?xml version="1.0"?>
<robot name="vertical_stick"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <xacro:property name="vertical_stick_z" value="0.0" />
  <xacro:property name="vertical_stick_height" value="0.55" />

  <xacro:property name="vertical_stick_x" value="0.0" />
  <xacro:property name="vertical_stick_y" value="0.0" />

  <xacro:property name="vertical_stick_height"      value="1.2" />
  <xacro:property name="vertical_stick_radius"      value="0.02" />
  <xacro:property name="vertical_stick_base_height" value="0.02" />
  <xacro:property name="vertical_stick_base_width"  value="0.15" />
  <xacro:property name="vertical_stick_mass"        value="0.2" /> 
  <xacro:property name="vertical_stick_mu"          value="500.0" /> 
  <joint name="vertical_stick_joint" type="fixed" >
    <parent link="vertical_stick_base_link" />
    <origin xyz="${vertical_stick_x} ${vertical_stick_y} ${vertical_stick_z+vertical_stick_height+vertical_stick_base_height}" rpy="0 0 0" />
    <child link="vertical_stick_link" />
  </joint> 
  <link name="vertical_stick_link">
    <inertial>
      <mass value="${vertical_stick_mass/2.0}" />
      <origin xyz="0 0 ${vertical_stick_height/2}" />
      <inertia ixx="${vertical_stick_mass/20.0}" ixy="0"  ixz="0"
               iyy="${vertical_stick_mass/20.0}" iyz="0"
               izz="${vertical_stick_mass/200.}" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${vertical_stick_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${vertical_stick_radius}" length="${vertical_stick_height}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${vertical_stick_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${vertical_stick_radius}" length="${vertical_stick_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="vertical_stick_link">
    <material>Gazebo/BumpyMetal</material>
    <mu1>${vertical_stick_mu}</mu1>
    <mu2>${vertical_stick_mu}</mu2>
    <kp>100000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
    <turnGravityOff>false</turnGravityOff>
    <dampingFactor>0.001</dampingFactor>
  </gazebo>

  <link name="vertical_stick_base_link">
    <inertial>
      <mass value="${vertical_stick_mass/2.0}" />
      <origin xyz="${vertical_stick_x} ${vertical_stick_y} ${vertical_stick_z+vertical_stick_height+vertical_stick_base_height/2}" rpy="0 0 0" />
      <inertia ixx="${vertical_stick_mass/20.0}" ixy="0"  ixz="0"
               iyy="${vertical_stick_mass/20.0}" iyz="0"
               izz="${vertical_stick_mass/200.}" />
    </inertial> 
    <visual>
      <origin xyz="${vertical_stick_x} ${vertical_stick_y} ${vertical_stick_z+vertical_stick_height+vertical_stick_base_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${vertical_stick_base_width} ${vertical_stick_base_width} ${vertical_stick_base_height}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="${vertical_stick_x} ${vertical_stick_y} ${vertical_stick_z+vertical_stick_height+vertical_stick_base_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${vertical_stick_base_width} ${vertical_stick_base_width} ${vertical_stick_base_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="vertical_stick_base_link">
    <material>Gazebo/RustyBarrel</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>100000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
    <turnGravityOff>false</turnGravityOff>
    <dampingFactor>0.001</dampingFactor>
  </gazebo>
  <gazebo>
    <canonicalBody>vertical_stick_base_link</canonicalBody>
  </gazebo>

</robot>
